markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: wangfan0840
author: "wangfan0840"
email: wangfan0840#163.com
name: "vevan's Blog"
baseurl: /
url: https://wangfan0840.github.io/
domain: https://wangfan0840.github.io/

all_categories: [
  ["sqoop", "Sqoop相关","/sqoop/index.html"],
  ["hadoop", "hadoop相关","/hadoop"],
  ["mac", "mac相关", "/mac"],
  ["web", "Web相关","/web"],
  ["linux", "Linux相关","/linux"],
  ["git", "git相关","/git"],
  ["other", "杂记","/other"],
  ["read", "书摘","/read"],
  ["about", "关于","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
#plugins: [jekyll-paginate]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
